/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from '../../common'

export interface IDCInterface extends utils.Interface {
  functions: {
    'nameExpires(string)': FunctionFragment
    'ownerOf(string)': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic: 'nameExpires' | 'ownerOf'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'nameExpires',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'ownerOf',
    values: [PromiseOrValue<string>]
  ): string

  decodeFunctionResult(functionFragment: 'nameExpires', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result

  events: {}
}

export interface IDC extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: IDCInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    nameExpires(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    ownerOf(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>
  }

  nameExpires(
    name: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  ownerOf(
    name: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>

  callStatic: {
    nameExpires(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    ownerOf(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>
  }

  filters: {}

  estimateGas: {
    nameExpires(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    ownerOf(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>
  }

  populateTransaction: {
    nameExpires(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    ownerOf(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>
  }
}
